config/routes.rb
CreuRoja::Application.routes.draw do

	root 'locations#map'

	
	get '/home' => 'static_pages#home'
	get '/contact' => 'static_pages#contact'
	get '/about' => 'static_pages#about'
	get '/signin' => 'sessions#new'
	get '/login' => 'sessions#new'
	get '/signout' => 'sessions#destroy'
	get '/logout' => 'sessions#destroy'
	get '/map' => 'locations#map'
	post '/users/:id' => 'users#update'
	get '/email_sent' => 'static_pages#email_sent'
	get '/services/graphic' => 'services#graphic'
	get '/locations/map' => 'locations#map'
	get '/logs' => 'logs#index'

	resources :users do
		resources :services
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :services do
		resources :vehicles
	end
	resources :assemblies
	resources :vehicles
	resources :locations
	resources :service_users, only: [:create, :update, :destroy]
	resources :location_services, only: [:create, :update, :destroy]
	resources :assembly_locations, only: [:create, :update, :destroy]
	resources :user_assemblies, only: [:create, :update, :destroy]
	resources :vehicle_services, only: [:create, :update, :destroy]
	resources :vehicle_assemblies, only: [:create, :update, :destroy]
	resources :password_reset, only: [:new, :create, :edit, :update]
	resources :vehicle_positions, only: [:index, :create]
	resources :issues

end

app/models/service.rb
class Service < ActiveRecord::Base
	default_scope { order(base_time: :desc) }
	scope :unfinished_before, ->(time) { where("end_time > ?", time) }
	scope :not_archived, -> { where(archived: false) }
	scope :public_data, -> { select(:id, :name, :updated_at, :code, :description, :base_time, :start_time, :end_time, :archived) }
	
	belongs_to :assembly
	has_many :vehicle_services, dependent: :destroy
	has_many :vehicles, through: :vehicle_services
	has_many :service_users, dependent: :destroy
	has_many :users, through: :service_users
	has_many :location_services, dependent: :destroy
	has_many :locations, through: :location_services
	
	validates :name, presence: true
	validates :assembly_id, presence: true
	validates :base_time, presence: true
	validates :start_time, presence: true
	validates :end_time, presence: true
	
	def add_location(location)
		location_services.create(location_id: location.id)
	end
	
	def add_vehicle(vehicle)
		vehicle_services.create(vehicle_id: vehicle.id)
	end
	
	def add_user(user, user_position)
		service_users.create(user_id: user.id, user_position: user_position)
	end
	
	def add_user_to_location(user, user_position, location)
		service_users.create(user_id: user.id, location_id: location.id, user_position: user_position)
	end
	
	def add_user_to_vehicle(user, user_position, vehicle)
		service_users.create(user_id: user.id, vehicle_id: vehicle.id, user_position: user_position)
	end
	
	def first_location_id
		locations.first.id unless locations.first.nil?
	end
	
	def expired?
		Time.now > end_time 
	end
	
	def in_base_time?(time = Time.now)
		base_time <= time && time < start_time
	end
	
	def started?(time = Time.now)
		start_time <= time && time < end_time
	end
	
	def finished?(time = Time.now)
		time >= end_time
	end
	
	def self.last_date
		Service.order("end_time DESC").first.end_time
	end
	
	def self.pending_services(user)
		Service.unfinished_before(Time.now.to_s).where(assembly_id: user.assembly_ids)
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_filter :signed_in_user
	before_filter :is_valid_user, except: [:show, :index]
	before_action :set_vehicle, only: [:index]
	before_action :set_user, only: [:index]
	before_action :set_service, only: [:show, :edit, :update, :destroy]

	# GET /services
	# GET /services.json
	def index
		@services = services
	end
	
	# GET /services/graphic
	def graphic
		@services = services
		@date = if params[:date]
			Date.new(params[:date][:year].to_i,params[:date][:month].to_i,params[:date][:day].to_i)
		else
			Date.today
		end
	end

	# GET /services/1
	# GET /services/1.json
	def show
		@vehicle_service = VehicleService.new
		@location_service = LocationService.new
		@service_user = ServiceUser.new
	end

	# GET /services/new
	def new
		@service = Service.new
	end

	# GET /services/1/edit
	def edit
	end

	# POST /services
	# POST /services.json
	def create
		@service = Service.new(service_params)

		respond_to do |format|
			if log_action_result @service, @service.save
				format.html { redirect_to @service, notice: I18n.t(:service_created) }
				format.json { render action: 'show', status: :created, location: @service }
			else
				format.html { render action: 'new' }
				format.json { render json: @service.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /services/1
	# PATCH/PUT /services/1.json
	def update
		respond_to do |format|
			if log_action_result @service, @service.update(service_params)
				format.html { redirect_to @service, notice: I18n.t(:service_updated) }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @service.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /services/1
	# DELETE /services/1.json
	def destroy
		log_action_result @service
		@service.destroy
		respond_to do |format|
			format.html { redirect_to services_url }
			format.json { head :no_content }
		end
	end

	private
		def set_vehicle
			@vehicle = (params[:vehicle_id]) ? Vehicle.find(params[:vehicle_id]) : nil
		end
		
		def set_user
			@user = (params[:user_id]) ? User.find(params[:user_id]) : nil
		end
		
		def services
			(@vehicle) ? @vehicle.services : ((@user) ? @user.services : Service.all )
		end
		
		# Use callbacks to share common setup or constraints between actions.
		def set_service
			@service = Service.find(params[:id]) || not_found
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def service_params
			params.require(:service).permit(:name, :description, :archived, :assembly_id, :base_time, :start_time, :end_time, :code)
		end
		
		def is_valid_user
			redirect_to root_url unless current_user && current_user.allowed_to?(:manage_services)
		end
end

app/helpers/services_helper.rb
module ServicesHelper
	#NOTE:
	#This methods are extracted from the VIEWS to increase readability. 
	#They are thought for creating an array of values usable in select forms.
	
	#Service: Service for which the vehicles are requested
	def get_available_vehicles(service)
		availables = []
		Vehicle.where(operative: true).each do |vehicle|
			#If the service already has the vehicle, ignore
			unless service.vehicles.include?(vehicle)
				is_available = true
				#Assignment: Services for which the vehicle is already assigned
				vehicle.services.each do |assignment|
					#If the assigned services match in time with the service wanted, mark it as not available
					is_available = false if (service.base_time < assignment.end_time && service.end_time > assignment.base_time)
				end
				availables << [vehicle.tag, vehicle.id] if is_available
			end
		end
		availables
	end
	
	def get_available_locations(service)
		locations = []
		Location.active_locations.each do |location|
			locations << [location.name, location.id] unless service.locations.include?(location)
		end
		locations
	end
	
	def get_available_users(service)
		availables = []
		User.where(active: true).each do |user|
			unless service.users.include?(user)
				is_available = true
				user.services.each do |assignment|
					is_available = false if (service.base_time < assignment.end_time && service.end_time > assignment.base_time)
				end
			end
			availables << [user.full_name, user.id] if is_available
		end
		availables
	end
	
	def locations_for_user_service(locations)
		available_locations = []
		available_locations << [I18n.t(:user_goes_in_vehicle), -1]
		locations.each do |location|
			available_locations << [location.name, location.id]
		end
		available_locations
	end
	
	def vehicles_for_user_service(vehicles)
		available_vehicles = []
		available_vehicles << [I18n.t(:user_goes_to_location), -1]
		vehicles.each do |vehicle|
			available_vehicles << [vehicle.indicative, vehicle.id]
		end
		available_vehicles
	end
end

app/views/services/_add_location.html.erb
<div id="assign_service_to_location" class="add_to_service_form">
	<% available_locations = get_available_locations @service %>
	<% unless available_locations.empty? %>
		<strong> <%= t(:form_service_assign_location) %>: </strong>
		<%= form_for(@location_service) do |f| %>
		<% if @location_service.errors.any? %>
			<div id="error_explanation">
				<h2><%= "#{pluralize(@location_service.errors.count, "error")} #{t(:form_errors_found)}:" %></h2>
				<ul>
				<% @location_service.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
		<%= f.hidden_field :service_id, :value => @service.id %>
		
		<%= f.label :location_id, t(:form_add_location_to_service_location_id) %>
		<%= f.select(:location_id, available_locations) %>

		<div class="location_service_location_id">
			<%= f.submit t(:form_add_location_to_service_submit) %>
		</div>
		<% end %>
	<% end %>
</div>

app/views/services/_add_user.html.erb
<div id="assign_user_to_service" class="add_to_service_form">
	<% available_users = get_available_users @service %>
	<% unless available_users.empty? %>
		<strong> <%= t(:form_service_assign_user) %>: </strong>
		<%= form_for(@service_user) do |f| %>
			<% if @service_user.errors.any? %>
				<div id="error_explanation">
					<h2><%= "#{pluralize(@service_user.errors.count, "error")} #{t(:form_errors_found)}:" %></h2>
					<ul>
					<% @service_user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
					</ul>
				</div>
			<% end %>
			
			<%= f.hidden_field :service_id, :value => @service.id %>

			<p id="warning_only_location_or_vehicle">
			<%= t(:form_add_user_to_service_warning_only_location_or_vehicle) %></p><br>
			
			<%= f.label :user_id, t(:form_add_user_to_service_user_id) %>
			<%= f.select :user_id, available_users %>
			
			<%= f.label :user_position, t(:form_add_user_to_service_doc) %>
			<%= f.select :user_position, UserType.available_types %>
			
			<%= f.label :location_id, t(:form_add_user_to_service_location_id) %>
			<%= f.select :location_id, locations_for_user_service(@service.locations) %>
			
			<%= f.label :vehicle_id, t(:form_add_user_to_service_vehicle_id) %>
			<%= f.select :vehicle_id, vehicles_for_user_service(@service.vehicles) %>

			<div class="service_user_submit">
				<%= f.submit t(:form_add_user_to_service_submit) %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/services/_add_vehicle.html.erb
<div id="assign_vehicle_to_service" class="add_to_service_form">
	<% available_vehicles = get_available_vehicles @service %>
	<% unless available_vehicles.empty? %>
		<strong> <%= t(:form_service_assign_vehicle) %>: </strong>
		<%= form_for(@vehicle_service) do |f| %>
		<% if @vehicle_service.errors.any? %>
			<div id="error_explanation">
				<h2><%= "#{pluralize(@vehicle_service.errors.count, "error")} #{t(:form_errors_found)}:" %></h2>
				<ul>
				<% @vehicle_service.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
		<%= f.hidden_field :service_id, :value => @service.id %>
		
		<%= f.label :vehicle_id, t(:form_add_vehicle_to_service_vehicle_id) %>
		<%= f.select(:vehicle_id, available_vehicles) %>

		<div class="vehicle_service_submit">
			<%= f.submit t(:form_add_vehicle_to_service_submit) %>
		</div>
		<% end %>
	<% end %>
</div>

app/views/services/_assigned_locations.html.erb
<div id="assigned_locations">
	<strong> <%= t(:form_service_assigned_locations) %>: </strong>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_location_name) %></th>
				<th><%= t(:form_location_description) %></th>
				<th><%= t(:form_location_address) %></th>
				<th><%= t(:form_location_phone) %></th>
				<th><%= t(:form_location_active) %></th>
				<th></th>
				<% if current_user.allowed_to?(:assign_service_to_location) %>
					<th></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
		<% @service.locations.each do |location| %>
			<tr>
				<td><%= location.name %></td>
				<td><%= location.description %></td>
				<td><%= location.address %></td>
				<td><%= location.phone %></td>
				<td><%= location.location_type %></td>
				
				<td><%= link_to t(:resource_show), location %></td>
				<% if current_user.allowed_to?(:assign_service_to_location) %>
					<% service_location = location.location_services.find_by_service_id(@service.id) %>
					<td><%= link_to t(:resource_destroy), service_location, method: :delete, data: { confirm: t(:resource_destroy_confirm) } %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
	</table>
</div>

app/views/services/_assigned_users.html.erb
<div id="assigned_users">
	<strong> <%= t(:form_service_assigned_users) %>: </strong>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_user_name) %></th>
				<th><%= t(:form_user_email) %></th>
				<th><%= t(:form_user_phone) %></th>
				<th><%= t(:form_user_notes) %></th>
				<th><%= t(:form_user_location) %></th>
				<th><%= t(:form_user_position) %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @service.users.each do |user| %>
			<% service_user = ServiceUser.where(service_id: @service.id, user_id: user.id).first %>
			<% location = service_user.location %>
			<% vehicle = service_user.vehicle %>
				<tr>
					<td><%= "#{user.name} #{user.surname}" %></td>
					<td><%= user.email %></td>
					<td><%= user.phone %></td>
					<td><%= service_user.notes %></td>
					<td>
					<%= form_for(service_user) do |f| %>
						<%= f.label :location_id, t(:form_add_user_to_service_location_id) %>
						<%= f.select :location_id, locations_for_user_service(@service.locations) %>
						
						<%= f.label :vehicle_id, t(:form_add_user_to_service_vehicle_id) %>
						<%= f.select :vehicle_id, vehicles_for_user_service(@service.vehicles) %>
						
						<div class="service_user_submit">
							<%= f.submit t(:form_add_user_to_service_submit) %>
						</div>
					<% end %>
					</td>
					<td><%= service_user.user_position %></td>
					<td><%= link_to t(:resource_show), user %></td>
					<% if current_user.allowed_to?(:assign_user_to_service) %>
						<% user_service = user.service_users.find_by_service_id(@service.id) %>
						<td><%= link_to t(:resource_destroy), user_service, method: :delete, data: { confirm: t(:resource_destroy_confirm) } %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/services/_assigned_vehicles.html.erb
<div id="assigned_vehicles">
	<strong> <%= link_to t(:form_service_assigned_vehicles), service_vehicles_path(@service) %>: </strong>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_vehicle_indicative) %></th>
				<th><%= t(:form_vehicle_license) %></th>
				<th><%= t(:form_vehicle_brand) %></th>
				<th><%= t(:form_vehicle_model) %></th>
				<th><%= t(:form_vehicle_type) %></th>
				<th><%= t(:form_vehicle_places) %></th>
				<th></th>
				<% if current_user.allowed_to?(:assign_vehicle_to_service) %>
					<th></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
		<% @service.vehicles.each do |vehicle| %>
			<tr>
				<td><%= vehicle.indicative %></td>
				<td><%= vehicle.license %></td>
				<td><%= vehicle.brand %></td>
				<td><%= vehicle.model %></td>
				<td><%= vehicle.vehicle_type %></td>
				<td><%= vehicle.places %></td>
				<td><%= link_to t(:resource_show), vehicle %></td>
				<% if current_user.allowed_to?(:assign_vehicle_to_service) %>
					<% vehicle_service = vehicle.vehicle_services.find_by_service_id(@service.id) %>
					<td><%= link_to t(:resource_destroy), vehicle_service, method: :delete, data: { confirm: t(:resource_destroy_confirm) } %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
	</table>
</div>

app/views/services/_day_chooser.html.erb
<div class="date-selector">
	<%= form_tag 'graphic', method: :get do %>
		<%= select_date @date, prefix: :date %>
		<%= submit_tag t(:form_service_submit) %>
	<% end %>
</div>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
	<% if @service.errors.any? %>
		<div id="error_explanation">
			<h2><%= "#{pluralize(@service.errors.count, "error")} #{t(:form_errors_found)}:" %></h2>

			<ul>
			<% @service.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<% user_assemblies = current_user.assemblies.collect { |assembly| [ assembly.name, assembly.id ] } %>

	<div class="field">
		<%= f.label :name, t(:form_service_name) %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description, t(:form_service_description) %><br>
		<%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :assembly_id, t(:form_service_assembly) %><br>
		<%= f.select :assembly_id, user_assemblies %>
	</div>
	<div class="field date_field">
		<%= f.label :base_time, t(:form_service_base_time) %><br>
		<%= f.datetime_select :base_time %>
	</div>
	<div class="field date_field">
		<%= f.label :start_time, t(:form_service_start_time) %><br>
		<%= f.datetime_select :start_time %>
	</div>
	<div class="field date_field">
		<%= f.label :end_time, t(:form_service_end_time) %><br>
		<%= f.datetime_select :end_time %>
	</div>
	<div class="field">
		<%= f.label :code, t(:form_service_code) %><br>
		<%= f.text_field :code %>
	</div>
	<div class="field">
		<%= f.label :doc, t(:form_add_vehicle_to_service_doc) %>
		<%= f.number_field(:doc, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :due, t(:form_add_vehicle_to_service_due) %>
		<%= f.number_field(:due, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :tes, t(:form_add_vehicle_to_service_tes) %>
		<%= f.number_field(:tes, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :ci, t(:form_add_vehicle_to_service_ci) %>
		<%= f.number_field(:ci, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :asi, t(:form_add_vehicle_to_service_asi) %>
		<%= f.number_field(:asi, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :btp, t(:form_add_vehicle_to_service_btp) %>
		<%= f.number_field(:btp, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :b1, t(:form_add_vehicle_to_service_b1) %>
		<%= f.number_field(:b1, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :acu, t(:form_add_vehicle_to_service_acu) %>
		<%= f.number_field(:acu, { value: 0 }) %>
	</div>
	<div class="field">
		<%= f.label :per, t(:form_add_vehicle_to_service_per) %>
		<%= f.number_field(:per, { value: 0 }) %>
	</div>
	<div class="actions">
		<%= f.submit t(:form_service_submit) %>
	</div>
<% end %>

app/views/services/_join_service.html.erb
<div id="form_user_join_service">
	<%= form_for(@service_user) do |f| %>
		<% types = [] %>
		<% UserType.available_types(current_user).each do |ut| %>
			<% types << [t(ut.user_type.to_sym), ut.user_type] %>
		<% end %>
		<%= f.label :user_position, t(:form_add_user_to_service_doc) %>
		<%= f.select :user_position, types %>
		
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :service_id, value: @service.id %>
		
		<div class="service_user_submit">
			<%= f.submit t(:form_user_join_service) %>
		</div>
	<% end %>
</div>

app/views/services/edit.html.erb
<% provide(:title, t(:form_service_edit_title)) %>
<h1><%= t(:form_service_edit_title) %></h1>

<%= render 'form' %>

<%= link_to t(:resource_show), @service %> |
<%= link_to t(:resource_back), services_path %>

app/views/services/graphic.html.erb
<% provide(:title, t(:form_service_show_title)) %>

<h1><%= t(:service_list_title) %></h1>

<% day_services = @services.where(base_time: @date.beginning_of_day..@date.end_of_day) %>
<% not_occupied = "<td style=\"background-color: white; border:thin solid black; padding: 3px;\"></td>" %>
<% base = "<td style=\"background-color: green; border:thin solid black; padding: 3px;\"></td>" %>
<% started = "<td style=\"background-color: red; border:thin solid black; padding: 3px;\"></td>" %>

<%= render 'day_chooser' %>

<div id="services_graphic">
	<table cellpadding="10" cellspacing="0">
		<thead>
			<tr style="outline:1px solid black;">
				<th><%= t(:form_service_name) %></th>
				<th><%= t(:form_service_code) %></th>
				<th><%= t(:vehicle) %></th>
				<% (6..23).each do |hour| %>
					<th align="left" colspan="4" style="border:1px solid black;"><%= hour %></th>
				<% end %>
				<% (0..5).each do |hour| %>
					<th align="left" colspan="4" style="border:1px solid black;"><%= hour %></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% day_services.each do |service| %>
			<tr style="outline:1px solid black;" >
				<td><%= link_to service.name, service %></td>
				<td><%= link_to service.code, service %></td>
				<td>
					<% service.vehicles.each do |vehicle| %>
						<%= raw "#{link_to vehicle, vehicle}" %>
						<% driver = vehicle.driver(service) %>
						<% unless driver.nil? %>
							<% driver_name = "#{driver.name} #{driver.surname}" %>
							<%= raw " - #{link_to driver_name, user_path(driver.user_id)}" %><br>
						<% end %>
					<% end %>
				</td>
				<% (6..23).each do |hour| %>
					<% (0..3).each do |quarter| %>
						<% time = service.base_time.change(hour: hour, min: quarter * 15) %>
						<% if service.in_base_time? time %>
							<%= raw base %>
						<% elsif service.started? time %>
							<%= raw started %>
						<% else %>
							<%= raw not_occupied %>
						<% end %>
					<% end %>
				<% end %>
				<% (0..5).each do |hour| %>
					<% (0..3).each do |quarter| %>
						<% time = service.base_time.change(hour: hour, min: quarter * 15) %>
						<% time = service.base_time.tomorrow %>
						<% if service.in_base_time? time %>
							<%= raw base %>
						<% elsif service.started? time %>
							<%= raw started %>
						<% else %>
							<%= raw not_occupied %>
						<% end %>
					<% end %>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to t(:form_service_new), new_service_path %>
<%= link_to t(:resource_back), services_path %>

app/views/services/index.html.erb
<% provide(:title, t(:service_list_title)) %>
<h1><%= t(:service_list_title) %></h1>

<%= link_to t(:form_service_graphic), services_graphic_path %> |
<%= link_to t(:form_service_new), new_service_path %>

<br><br> 

<div id="services_index">
	<table>
		<thead>
			<tr>
				<th><%= t(:form_service_name) %></th>
				<th><%= t(:form_service_description) %></th>
				<th><%= t(:form_service_assembly) %></th>
				<th><%= t(:form_service_base_time) %></th>
				<th><%= t(:form_service_start_time) %></th>
				<th><%= t(:form_service_finish_time) %></th>
				<th><%= t(:form_service_code) %></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @services.each do |service| %>
				<tr<%= raw " class=\"archived_service\"" if service.archived %>>
				<td><%= service.name %></td>
				<td><%= service.description %></td>
				<td><%= service.assembly.name %></td>
				<td><%= service.base_time %></td>
				<td><%= service.start_time %></td>
				<td><%= service.end_time %></td>
				<td><%= service.code %></td>
				<td><%= link_to t(:resource_show), service %></td>
				<% if current_user.allowed_to?(:manage_services) %>
					<td><%= link_to t(:resource_edit), edit_service_path(service) %></td>
					<% if service.expired? && !service.archived %>
						<td><%= link_to t(:archive_service), service_path(service, :service => { :archived => true }), method: :put, data: { confirm: t(:resource_destroy_confirm) } %></td>
					<% end %>
				<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/services/new.html.erb
<% provide(:title, t(:form_service_new)) %>
<h1><%= t(:form_service_new) %></h1>

<%= render 'form' %>

<%= link_to t(:resource_back), services_path %>

app/views/services/show.html.erb
<% provide(:title, t(:form_service_show_title)) %>
<h1> <%= t(:form_service_show_title) %> </h1>
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<div id="service_details">
	<strong><%= t(:form_service_name) %>:</strong>
	<%= @service.name %>
	<br>
	<strong><%= t(:form_service_description) %>:</strong>
	<%= @service.description %>
	<br>
	<strong><%= t(:form_service_assembly) %>:</strong>
	<%= @service.assembly.name %>
	<br>
	<strong><%= t(:form_service_base_time) %>:</strong>
	<%= @service.base_time %>
	<br>
	<strong><%= t(:form_service_start_time) %>:</strong>
	<%= @service.start_time %>
	<br>
	<strong><%= t(:form_service_end_time) %>:</strong>
	<%= @service.end_time %>
	<br>
	<strong><%= t(:form_service_code) %>:</strong>
	<%= @service.code %>
	<br>
	<strong><%= t(:form_service_archived) %>:</strong>
	<%= @service.archived %>
	<br>
</div>
<% if current_user.allowed_to?(:manage_services) %>
	<% unless @service.expired? || @service.archived %>
		<div class="assignments">
			<%= render 'assigned_locations' %>
			<%= render 'add_location' if current_user && current_user.allowed_to?(:assign_service_to_location) %>

			<%= render 'assigned_vehicles' unless @service.vehicles.empty? %>
			<%= render 'add_vehicle' if current_user && current_user.allowed_to?(:assign_vehicle_to_service) %>

			<% unless @service.locations.empty?%>
				<%= render 'assigned_users' unless @service.users.empty? %>
				<%= render 'add_user' if current_user && current_user.allowed_to?(:assign_user_to_service) %>
			<% end %>
		</div>
	<% end %>
<% else %>
	<%= render 'join_service' unless current_user.goes_to?(@service) %>
<% end %>

<%= link_to t(:resource_edit), edit_service_path(@service) if current_user.allowed_to?(:manage_services) %> |
<%= link_to t(:resource_back), services_path %>