config/routes.rb
CreuRoja::Application.routes.draw do

	root 'locations#map'

	
	get '/home' => 'static_pages#home'
	get '/contact' => 'static_pages#contact'
	get '/about' => 'static_pages#about'
	get '/signin' => 'sessions#new'
	get '/login' => 'sessions#new'
	get '/signout' => 'sessions#destroy'
	get '/logout' => 'sessions#destroy'
	get '/map' => 'locations#map'
	post '/users/:id' => 'users#update'
	get '/email_sent' => 'static_pages#email_sent'
	get '/services/graphic' => 'services#graphic'
	get '/locations/map' => 'locations#map'
	get '/logs' => 'logs#index'

	resources :users do
		resources :services
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :services do
		resources :vehicles
	end
	resources :assemblies
	resources :vehicles
	resources :locations
	resources :service_users, only: [:create, :update, :destroy]
	resources :location_services, only: [:create, :update, :destroy]
	resources :assembly_locations, only: [:create, :update, :destroy]
	resources :user_assemblies, only: [:create, :update, :destroy]
	resources :vehicle_services, only: [:create, :update, :destroy]
	resources :vehicle_assemblies, only: [:create, :update, :destroy]
	resources :password_reset, only: [:new, :create, :edit, :update]
	resources :vehicle_positions, only: [:index, :create]
	resources :issues

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	default_scope { order(vehicle_type: :asc, indicative: :asc) }
	
	has_many :vehicle_services, dependent: :destroy
	has_many :services, through: :vehicle_services
	has_many :vehicle_assemblies, dependent: :destroy
	has_many :assemblies, through: :vehicle_assemblies
	has_many :service_users, dependent: :destroy
	has_many :vehicle_positions, dependent: :destroy

	validates :indicative, presence: true
	validates :brand, presence: true
	validates :model, presence: true
	validates :license, presence: true
	validates :vehicle_type, presence: true
	validates :places, presence: true
	
	after_initialize :validate_licenses
	
	def to_s
		"#{indicative}"
	end
	
	def tag
		"#{indicative}, #{license}"
	end
	
	def add_to_service(service)
		vehicle_services.create(service_id: service.id)
	end
	
	def add_to_assembly(assembly)
		vehicle_assemblies.create(assembly_id: assembly.id)
	end
	
	def add_user_to_service_in_vehicle(user, service, user_position)
		service_users.create(user_id: user.id, service_id: service.id, user_position: user_position)
	end
	
	def translated_vehicle_type
		case vehicle_type
		when "alfa bravo"
			I18n.t(:vehicle_type_alfa_bravo)
		when "alfa mike"
			I18n.t(:vehicle_type_alfa_mike)
		when "mike"
			I18n.t(:vehicle_type_mike)
		when "romeo"
			I18n.t(:vehicle_type_romeo)
		when "tango"
			I18n.t(:vehicle_type_tango)
		else
			"dafuq"
		end
	end
	
	def driver(service)
		self.service_users.where(user_position: ["b1","btp","per"], service_id: service.id).first
	end
	
	def available?
		validate_licenses
	end
	
	def update_position(lat, lng)
		VehiclePosition.create!(vehicle_id: id, latitude: lat, longitude: lng)
	end
	
	def last_position
		self.vehicle_positions.last
	end

	protected
		def defaults
		end
		
		def validate_licenses
			self.operative = false if self.itv && self.itv < Date.today
			self.operative = false if self.sanitary_cert && self.sanitary_cert < Date.today
			self.save if self.operative == false
			self.operative
		end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	before_filter :signed_in_user
	before_filter :is_valid_user
	before_action :set_service, only: [:show, :index]
	before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

	# GET /vehicles
	# GET /vehicles.json
	def index
		@vehicles = vehicles
	end

	# GET /vehicles/1
	# GET /vehicles/1.json
	def show
	end

	# GET /vehicles/new
	def new
		@vehicle = Vehicle.new
	end

	# GET /vehicles/1/edit
	def edit
	end

	# POST /vehicles
	# POST /vehicles.json
	def create
		@vehicle = Vehicle.new(vehicle_params)

		respond_to do |format|
			if log_action_result @vehicle, @vehicle.save
				format.html { redirect_to @vehicle, notice: I18n.t(:vehicle_created) }
				format.json { render action: 'show', status: :created, location: @vehicle }
			else
				format.html { render action: 'new' }
				format.json { render json: @vehicle.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /vehicles/1
	# PATCH/PUT /vehicles/1.json
	def update
		respond_to do |format|
			if log_action_result @vehicle, @vehicle.update(vehicle_params)
				format.html { redirect_to @vehicle, notice: I18n.t(:vehicle_updated) }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @vehicle.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /vehicles/1
	# DELETE /vehicles/1.json
	def destroy
		log_action_result @vehicle
		@vehicle.destroy
		respond_to do |format|
			format.html { redirect_to vehicles_url }
			format.json { head :no_content }
		end
	end

	private
		def set_service
			@service = (params[:service_id]) ? Service.find(params[:service_id]) : nil
		end
		
		def vehicles
			(@service) ? @service.vehicles : current_user.vehicles
		end
		
		# Use callbacks to share common setup or constraints between actions.
		def set_vehicle
			@vehicle = vehicles.find(params[:id]) || not_found
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def vehicle_params
			params.require(:vehicle).permit(:brand, :model, :license, :indicative, :vehicle_type, :places, :notes, :operative, :itv, :sanitary_cert)
		end
		
		def is_valid_user
			redirect_to root_url unless current_user && current_user.allowed_to?(:manage_vehicles)
		end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_add_assemblies.html.erb
<div id="add_vehicle_to_assembly">
	<h3><%= t(:form_add_vehicle_to_assembly) %></h3>
	<% assemblies = [] %>
	<% Assembly.all.each do |assembly| %>
		<% assemblies << [assembly.name, assembly.id] unless @vehicle.assemblies.include?(assembly) %>
	<% end %>
	<%= form_for(VehicleAssembly.new) do |f| %>
		<%= f.hidden_field :vehicle_id, value: @vehicle.id %>
		
		<%= f.label :assembly_id, t(:form_vehicle_assemblies) %>
		<%= f.select :assembly_id, assemblies %>
		
		<%= f.submit t(:form_vehicle_submit) %>
	<% end %>
</div>

app/views/vehicles/_assemblies.html.erb
<div id="vehicle_assemblies">
	<h3><%= t(:vehicle_assemblies) %></h3>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_location_name) %></th>
				<th><%= t(:form_location_description) %></th>
				<th><%= t(:form_location_address) %></th>
				<th><%= t(:form_location_phone) %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @vehicle.assemblies.each do |assembly| %>
				<tr>
					<td><%= assembly.name %></td>
					<td><%= assembly.description %></td>
					<td><%= assembly.address %></td>
					<td><%= assembly.phone %></td>
					<% if current_user.allowed_to?(:manage_vehicles) %>
						<% vehicle_assembly = VehicleAssembly.where(vehicle_id: @vehicle.id, assembly_id: assembly.id).first %>
						<td><%= link_to t(:resource_destroy), vehicle_assembly, method: :delete %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
	<% if @vehicle.errors.any? %>
		<div id="error_explanation">
			<h2><%= "#{pluralize(@vehicle.errors.count, "error")} #{t(:form_errors_found)}:" %></h2>

			<ul>
			<% @vehicle.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
  
  <% available_vehicle = [[t(:vehicle_type_alfa_bravo), 'alfa bravo'],
			 [t(:vehicle_type_alfa_mike), 'alfa mike'],
			 [t(:vehicle_type_mike), 'mike'],
			 [t(:vehicle_type_romeo), 'romeo'],
			 [t(:vehicle_type_tango), 'tango']] %>

	<div class="field">
		<%= f.label :brand, t(:form_vehicle_brand) %><br>
		<%= f.text_field :brand %>
	</div>
	<div class="field">
		<%= f.label :model, t(:form_vehicle_model) %><br>
		<%= f.text_field :model %>
	</div>
	<div class="field">
		<%= f.label :license, t(:form_vehicle_license) %><br>
		<%= f.text_field :license %>
	</div>
	<div class="field">
		<%= f.label :indicative, t(:form_vehicle_indicative) %><br>
		<%= f.text_field :indicative %>
	</div>
	<div class="field">
		<%= f.label :vehicle_type, t(:form_vehicle_type) %><br>
		<%= f.select :vehicle_type, available_vehicle %>
	</div>
	<div class="field">
		<%= f.label :places, t(:form_vehicle_places) %><br>
		<%= f.number_field :places %>
	</div>
	<div class="field">
		<%= f.label :notes, t(:form_vehicle_notes) %><br>
		<%= f.text_field :notes %>
	</div>
	<div class="field">
		<%= f.label :operative, t(:form_vehicle_operative) %>
		<%= f.check_box :operative, { :checked => @vehicle.operative } %>
	</div>
	<div class="field">
		<%= f.label :itv, t(:form_vehicle_itv) %>
		<%= f.date_select :itv %>
	</div>
	<div class="field">
		<%= f.label :sanitary_cert, t(:form_vehicle_sanitary_cert) %>
		<%= f.date_select :sanitary_cert %>
	</div>
	<div class="actions">
		<%= f.submit t(:form_vehicle_submit) %>
	</div>
<% end %>

app/views/vehicles/edit.html.erb
<% provide(:title, t(:form_vehicle_edit_title)) %>
<h1><%= t(:form_vehicle_edit_title) %></h1>

<%= render 'form' %>

<%= link_to t(:resource_show), @vehicle %> |
<%= link_to t(:resource_back), vehicles_path %>

app/views/vehicles/index.html.erb
<% provide(:title, t(:vehicle_list_title)) %>
<h1><%= t(:vehicle_list_title) %></h1>

<%= link_to t(:form_vehicle_new), new_vehicle_path %>
<%= link_to t(:show_vehicle_positions), vehicle_positions_path %>

<br><br>

<table>
	<thead>
		<tr>
			<th><%= t(:form_vehicle_indicative) %></th>
			<th><%= t(:form_vehicle_brand) %></th>
			<th><%= t(:form_vehicle_license) %></th>
			<th><%= t(:form_vehicle_type) %></th>
			<th><%= t(:form_vehicle_places) %></th>
			<th><%= t(:form_vehicle_notes) %></th>
			<th><%= t(:form_vehicle_operative) %></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @vehicles.each do |vehicle| %>
			<tr>
			<td><%= vehicle.indicative %></td>
			<td><%= "#{vehicle.brand} #{vehicle.model}" %></td>
			<td><%= vehicle.license %></td>
			<td><%= vehicle.translated_vehicle_type %></td>
			<td><%= vehicle.places %></td>
			<td><%= vehicle.notes %></td>
			<td><%= vehicle.operative %></td>
			<td><%= link_to t(:resource_show), vehicle %></td>
			<% if current_user && current_user.allowed_to?(:manage_vehicles) %>
				<td><%= link_to t(:resource_edit), edit_vehicle_path(vehicle) %></td>
				<% if vehicle.available? %>
					<td><%= link_to t(:deactivate_vehicle), vehicle_path(vehicle, :vehicle => {:operative => false}), method: :put, data: { confirm: t(:resource_destroy_confirm) } %></td>
				<% else %>
					<td><%= link_to t(:reactivate_vehicle), vehicle_path(vehicle, :vehicle => {:operative => true}), method: :put %></td>
				<% end %>
			<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/vehicles/new.html.erb
<% provide(:title, t(:form_vehicle_new)) %>
<h1><%= t(:form_vehicle_new) %></h1>

<%= render 'form' %>

<%= link_to t(:resource_back), vehicles_path %>

app/views/vehicles/show.html.erb
<% provide(:title, t(:form_vehicle_show_title)) %>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong><%= t(:form_vehicle_brand) %>:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong><%= t(:form_vehicle_model) %>:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong><%= t(:form_vehicle_license) %>:</strong>
  <%= @vehicle.license %>
</p>

<p>
  <strong><%= t(:form_vehicle_indicative) %>:</strong>
  <%= @vehicle.indicative %>
</p>

<p>
  <strong><%= t(:form_vehicle_type) %>:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong><%= t(:form_vehicle_places) %>:</strong>
  <%= @vehicle.places %>
</p>

<p>
  <strong><%= t(:form_vehicle_notes) %>:</strong>
  <%= @vehicle.notes %>
</p>

<p>
  <strong><%= t(:form_vehicle_operative) %>:</strong>
  <%= @vehicle.available? %>
</p>

<p>
  <strong><%= t(:form_vehicle_itv) %>:</strong>
  <%= @vehicle.itv %>
</p>

<p>
  <strong><%= t(:form_vehicle_sanitary_cert) %>:</strong>
  <%= @vehicle.sanitary_cert %>
</p>

<%= render "assemblies" if @vehicle.assemblies.count > 0 %>
<%= render "add_assemblies" if current_user.allowed_to?(:manage_vehicles) %>

<%= link_to t(:resource_edit), edit_vehicle_path(@vehicle) if current_user.allowed_to?(:manage_vehicles) %> |
<%= link_to t(:resource_back), vehicles_path %>