config/routes.rb
CreuRoja::Application.routes.draw do

	root 'locations#map'

	
	get '/home' => 'static_pages#home'
	get '/contact' => 'static_pages#contact'
	get '/about' => 'static_pages#about'
	get '/signin' => 'sessions#new'
	get '/login' => 'sessions#new'
	get '/signout' => 'sessions#destroy'
	get '/logout' => 'sessions#destroy'
	get '/map' => 'locations#map'
	post '/users/:id' => 'users#update'
	get '/email_sent' => 'static_pages#email_sent'
	get '/services/graphic' => 'services#graphic'
	get '/locations/map' => 'locations#map'
	get '/logs' => 'logs#index'

	resources :users do
		resources :services
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :services do
		resources :vehicles
	end
	resources :assemblies
	resources :vehicles
	resources :locations
	resources :service_users, only: [:create, :update, :destroy]
	resources :location_services, only: [:create, :update, :destroy]
	resources :assembly_locations, only: [:create, :update, :destroy]
	resources :user_assemblies, only: [:create, :update, :destroy]
	resources :vehicle_services, only: [:create, :update, :destroy]
	resources :vehicle_assemblies, only: [:create, :update, :destroy]
	resources :password_reset, only: [:new, :create, :edit, :update]
	resources :vehicle_positions, only: [:index, :create]
	resources :issues

end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
	default_scope { order(name: :asc, level: :asc) }
	default_scope { order(name: :asc) }
	scope :estate, -> { where(level: "estatal") }
	scope :autonomicas, -> { where(level: "autonomica") }
	scope :provincials, -> { where(level: "provincial") }
	scope :locals, -> { where(level: ["local","comarcal","delegation"]) }
	scope :independent_provincials, -> { provincials.where(depends_on: nil) }
	scope :independent_locals, -> { locals.where(depends_on: nil) }
	
	has_many :user_assemblies, dependent: :destroy
	has_many :users, through: :user_assemblies
	has_many :assembly_locations, dependent: :destroy
	has_many :locations, through: :assembly_locations
	has_many :vehicle_assemblies, dependent: :destroy
	has_many :vehicles, through: :vehicle_assemblies
	has_many :services
	has_many :children, class_name: "Assembly", foreign_key: "depends_on"
	
	before_validation :defaults
	
	validates :name, presence: true
	validates :level, presence: true
	validates :location_id, presence: true
	
	def office
		Location.find(location_id)
	end
	
	def address
		office.address
	end
	
	def phone
		office.phone
	end
	
	def parent
		Assembly.find(self.depends_on) if self.depends_on && Assembly.exists?(self.depends_on)
	end
	
	def add_vehicle(vehicle)
		vehicle_assemblies.create(vehicle_id: vehicle.id)
	end
	
	def add_user(user)
		user_assemblies.create(user_id: user.id)
	end
	
	def add_location(location)
		assembly_locations.create(location_id: location.id)
	end
	
	def managed_assemblies
		assemblies = []
		child_assemblies(assemblies)
		assemblies
	end
	
	def managed_ids
		ids = []
		child_ids(ids)
		ids
	end
	
	def self.not_locals
		Assembly.where.not(level: ["local","comarcal","delegation"])
	end
	
	def translated_level
		case level
		when "estatal"
			I18n.t(:level_state)
		when "autonomica"
			I18n.t(:level_region)
		when "provincial"
			I18n.t(:level_province)
		when "comarcal"
			I18n.t(:level_comarcal)
		when "local"
			I18n.t(:level_local)
		when "delegation"
			I18n.t(:level_delegation)
		else
			"dafuq"
		end
	end
	
	def to_s
		self.name
	end
	
	def find_parent_with_level(level, assembly = self)
		if(assembly.level == level || assembly.parent.nil?)
			assembly
		else
			find_parent_with_level(level, assembly.parent)
		end
	end
	
	def self.is_valid?(level)
		Assembly.exists?(level: level)
	end
	
	private
		def child_assemblies(assemblies, assembly = self)
			dependants = Assembly.where(depends_on: assembly.id)
			assemblies << assembly
			dependants.each { |child| child_assemblies(assemblies, child) } if dependants.count != 0
		end
		
		def child_ids(ids, assembly = self)
			dependants = Assembly.where(depends_on: assembly.id)
			ids << assembly.id
			dependants.each { |child| child_ids(ids, child) } if dependants.count != 0
		end
		
		def defaults
			self.depends_on = nil if self.depends_on == "-"
		end
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
	before_filter :signed_in_user
	before_filter :is_valid_user
	before_filter :set_assembly, only: [:show, :edit, :update, :destroy]
	
	def index
		@assemblies = Assembly.all
	end

	def new
		@assembly = Assembly.new
	end

	def create
		@assembly = Assembly.new(assembly_params)
		verify_parent(@assembly)
		if log_action_result @assembly, @assembly.save
			redirect_to @assembly
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		verify_parent(@assembly)
		log_action_result @assembly, @assembly.update(assembly_params)
		redirect_to @assembly
	end

	def destroy
		log_action_result @assembly
		@assembly.destroy
		redirect_to assemblies_url
	end
	
	private
		
		def assembly_params
			params.require(:assembly).permit(:name, :description, :level, :location_id, :depends_on)
		end
		
		def is_valid_user
			redirect_to root_url unless current_user.allowed_to?(:manage_assemblies)
		end
		
		def set_assembly
			@assembly = Assembly.find(params[:id])
		end
		
		def verify_parent(assembly)
			if assembly.depends_on == "-" || assembly.depends_on == 0
				assembly.depends_on = nil
			end
		end
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
	def assembly_levels
		[[I18n.t(:assembly_level_delegation), "delegation"], [I18n.t(:assembly_level_local), "local"], [I18n.t(:assembly_level_comarcal), "comarcal"], [I18n.t(:assembly_level_province), "provincial"], [I18n.t(:assembly_level_region), "autonomica"], [I18n.t(:assembly_level_state), "estatal"]]
	end
end

app/views/assemblies/_form.html.erb
<%= form_for(@assembly) do |f| %>
	<% if @assembly.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

			<ul>
			<% @assembly.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<% locations = [] %>
	<% Location.offices.each do |office| %>
		<% locations << [office.name, office.id] %>
	<% end %>
	
	<% parents = ["-"] %>
	<% Assembly.not_locals.each do |assembly| %>
		<% parents << ["#{assembly.translated_level} #{assembly.name}", assembly.id] %>
	<% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :level %><br>
		<%= f.select :level, assembly_levels %>
	</div>
	<div class="field">
		<%= f.label :location_id %><br>
		<%= f.select :location_id, locations %>
	</div>
	<div class="field">
		<%= f.label :depends_on %><br>
		<%= f.select :depends_on, parents %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/assemblies/_locations.html.erb
<h3><%= "#{@assembly.locations.count} #{I18n.t(:locations)}" %></h3>
<div id="assigned_locations">
	<table>
		<thead>
			<tr>
				<th><%= t(:form_location_name) %></th>
				<th><%= t(:form_location_description) %></th>
				<th><%= t(:form_location_address) %></th>
				<th><%= t(:form_location_phone) %></th>
				<th></th>
				<% if current_user.allowed_to?(:assign_location_to_assembly) %>
					<th></th>
				<% end %>
			</tr>
		</thead>
		<tbody>
		<% @assembly.locations.each do |location| %>
			<tr>
				<td><%= location.name %></td>
				<td><%= location.description %></td>
				<td><%= location.address %></td>
				<td><%= location.phone %></td>
				
				<td><%= link_to t(:resource_show), location %></td>
				<% if current_user.allowed_to?(:assign_location_to_assembly) %>
					<% assembly_location = location.assembly_locations.find_by_assembly_id(@assembly.id) %>
					<td><%= link_to t(:resource_unassign), assembly_location, method: :delete, data: { confirm: t(:resource_destroy_confirm) } %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
	</table>
</div>

app/views/assemblies/_users.html.erb
<div id="assembly_users">
	<h3><%= "#{@assembly.users.count} #{I18n.t(:user_list_title)}" %></h3>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_user_name) %></th>
				<th><%= t(:form_user_role) %></th>
				<th><%= t(:form_user_active) %></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @assembly.users.each do |user|%> 
				<tr>
				<td><%= "#{user.name} #{user.surname}" %></td>
				<td><%= user.translated_role %></td>
				<td><%= user.active %></td>
				<td><%= link_to t(:resource_show), user %></td>
				<td><%= link_to t(:resource_edit), edit_user_path(user) if current_user?(user) || current_user.allowed_to?(:manage_users) %></td>
				<% if user.active %>
					<% if current_user && current_user != user && current_user.allowed_to?(:destroy_users) %>
					<td><%= link_to t(:deactivate_user), user_path(user, :user => {:active => false}), method: :put, data: { confirm: t(:resource_destroy_confirm) } %></td>
					<% end %>
				<% else %>
					<% if current_user && current_user.allowed_to?(:destroy_users) %>
					<td><%= link_to t(:reactivate_user), user_path(user, :user => {:active => true}), method: :put %></td>
					<% end %>
				<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/assemblies/_vehicles.html.erb
<div id="assembly_vehicles">
	<h3><%= "#{@assembly.vehicles.count} #{I18n.t(:vehicle_list_title)}" %></h3>
	<table>
		<thead>
			<tr>
				<th><%= t(:form_vehicle_indicative) %></th>
				<th><%= t(:form_vehicle_brand) %></th>
				<th><%= t(:form_vehicle_license) %></th>
				<th><%= t(:form_vehicle_type) %></th>
				<th><%= t(:form_vehicle_places) %></th>
				<th><%= t(:form_vehicle_notes) %></th>
				<th><%= t(:form_vehicle_operative) %></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @assembly.vehicles.each do |vehicle| %>
				<tr>
				<td><%= vehicle.indicative %></td>
				<td><%= "#{vehicle.brand} #{vehicle.model}" %></td>
				<td><%= vehicle.license %></td>
				<td><%= vehicle.translated_vehicle_type %></td>
				<td><%= vehicle.places %></td>
				<td><%= vehicle.notes %></td>
				<td><%= vehicle.operative %></td>
				<td><%= link_to t(:resource_show), vehicle %></td>
				<% if current_user && current_user.allowed_to?(:manage_vehicles) %>
					<td><%= link_to t(:resource_edit), edit_vehicle_path(vehicle) %></td>
					<% if vehicle.available? %>
						<td><%= link_to t(:deactivate_vehicle), vehicle_path(vehicle, :vehicle => {:operative => false}), method: :put, data: { confirm: t(:resource_destroy_confirm) } %></td>
					<% else %>
						<td><%= link_to t(:reactivate_vehicle), vehicle_path(vehicle, :vehicle => {:operative => true}), method: :put %></td>
					<% end %>
				<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/assemblies/edit.html.erb
<h1>Editing assembly</h1>

<%= render 'form' %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

app/views/assemblies/index.html.erb
<% provide(:title, t(:assembly_list_title)) %>
<h1><%= t(:assembly_list_title) %></h1>

<%= link_to t(:form_assembly_new), new_assembly_path %>
<ul>
	<% @assemblies.estate.each do |estatal| %>
		<li>
			<%= link_to "#{estatal.translated_level} #{estatal.name} - #{estatal.address} - #{estatal.phone}", estatal %>
		</li>
		<ul>
			<% estatal.children.autonomicas.each do |autonomica| %>
				<li>
					<%= link_to "#{autonomica.translated_level} #{autonomica.name} - #{autonomica.address} - #{autonomica.phone}", autonomica %>
				</li>
				<ul>
					<% autonomica.children.provincials.each do |provincial| %>
						<li>
							<%= link_to "#{provincial.translated_level} #{provincial.name} - #{provincial.address} - #{provincial.phone}", provincial %>
						</li>
						<ul>
							<% provincial.children.locals.each do |local| %>
								<li>
									<%= link_to "#{local.translated_level} #{local.name} - #{local.address} - #{local.phone}", local %>
								</li>
							<% end %>
						</ul>
					<% end %>
				</ul><br>
			<% end %>
		</ul>
	<% end %>
	<% if @assemblies.independent_provincials.count > 0 %>
		<ul>
			<li>
				<%= t(:unclassified_provincial_assemblies) %>
				<% @assemblies.independent_provincials.each do |provincial| %>
					<li>
						<%= link_to "#{provincial.translated_level} #{provincial.name} - #{provincial.address} - #{provincial.phone}", provincial %>
					</li>
					<ul>
						<% provincial.children.locals.each do |local| %>
							<li>
								<%= link_to "#{local.translated_level} #{local.name} - #{local.address} - #{local.phone}", local %>
							</li>
						<% end %>
					</ul>
				<% end %>
			</li>
		</ul>
	<% end %>
	<% if @assemblies.independent_locals.count > 0 %>
		<ul>
			<li>
				<%= t(:unclassified_local_assemblies) %>
				<% @assemblies.independent_locals.each do |local| %>
					<li>
						<%= link_to "#{local.translated_level} #{local.name} - #{local.address} - #{local.phone}", local %>
					</li>
				<% end %>
			</li>
		</ul>
	<% end %>
</ul>

app/views/assemblies/new.html.erb
<% provide(:title, t(:form_assembly_new)) %>
<h1><%= t(:form_assembly_new) %></h1>

<%= render 'form' %>

<%= link_to t(:resource_back), assemblies_path %>

app/views/assemblies/show.html.erb
<% provide(:title, t(:form_assembly_show_title)) %>

<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<h1><%= @assembly.translated_level %> <%= @assembly.name %></h1>

<%= link_to t(:resource_edit), edit_assembly_path(@assembly) if current_user.allowed_to?(:manage_assemblies) %> |
<%= link_to t(:resource_back), assemblies_path %>

<p>
	<strong><%= t(:form_location_description) %>:</strong>
	<%= @assembly.description %>
</p>

<p>
	<strong><%= t(:form_location_address) %>:</strong>
	<%= @assembly.address %>
</p>

<p>
	<strong><%= t(:form_location_phone) %>:</strong>
	<%= @assembly.phone %>
</p>

<% if @assembly.parent %>
	<p>
	<strong><%= t(:form_assembly_parent) %>:</strong>
	<%= link_to @assembly.parent.name, @assembly.parent %>
	</p>
<% end %>

<p>
	<strong><%= t(:location) %>:</strong>
	<%= link_to @assembly.office.name, @assembly.office %>
</p>

<%= render 'users' %>
<%= render 'vehicles' %>
<%= render 'locations' %>