config/routes.rb
CreuRoja::Application.routes.draw do

	root 'locations#map'

	
	get '/home' => 'static_pages#home'
	get '/contact' => 'static_pages#contact'
	get '/about' => 'static_pages#about'
	get '/signin' => 'sessions#new'
	get '/login' => 'sessions#new'
	get '/signout' => 'sessions#destroy'
	get '/logout' => 'sessions#destroy'
	get '/map' => 'locations#map'
	post '/users/:id' => 'users#update'
	get '/email_sent' => 'static_pages#email_sent'
	get '/services/graphic' => 'services#graphic'
	get '/locations/map' => 'locations#map'
	get '/logs' => 'logs#index'

	resources :users do
		resources :services
	end
	resources :sessions, only: [:new, :create, :destroy]
	resources :services do
		resources :vehicles
	end
	resources :assemblies
	resources :vehicles
	resources :locations
	resources :service_users, only: [:create, :update, :destroy]
	resources :location_services, only: [:create, :update, :destroy]
	resources :assembly_locations, only: [:create, :update, :destroy]
	resources :user_assemblies, only: [:create, :update, :destroy]
	resources :vehicle_services, only: [:create, :update, :destroy]
	resources :vehicle_assemblies, only: [:create, :update, :destroy]
	resources :password_reset, only: [:new, :create, :edit, :update]
	resources :vehicle_positions, only: [:index, :create]
	resources :issues

end

app/views/layouts/_header.html.erb
<header class="header">
	<div id="logo">
		<%= link_to image_tag("logomenu.png"), root_url, :title => t(:show_beta) %>
	</div>
	<% if signed_in? %>
	<nav class="nav_menu">
		<ul class ="nav_menu">
			<li> <%= link_to t(:map), root_url %> </li>
			<% if current_user.allowed_to?(:see_user_list) || current_user.allowed_to?(:see_vehicle_list) || current_user.allowed_to?(:see_service_list) || current_user.allowed_to?(:see_location_list) %>
				<li> <%= t(:menu_resources) %>
					<ul class="sub_menu">
						<% if current_user.allowed_to?(:see_user_list) %>
							<li> <%= link_to t(:user_list_title), users_url %>
						<% end %>
						<% if current_user.allowed_to?(:see_vehicle_list) %>
							<li> <%= link_to t(:vehicle_list_title), vehicles_url %>
						<% end %>
						<% if current_user.allowed_to?(:see_service_list) %>
							<li> <%= link_to t(:service_list_title), services_url %>
						<% end %>
						<% if current_user.allowed_to?(:see_location_list) %>
							<li> <%= link_to t(:location_list_title), locations_url %>
						<% end %>
						<% if current_user.allowed_to?(:see_assemblies) %>
							<li> <%= link_to t(:assembly_list_title), assemblies_url %>
						<% end %>
						<% if current_user.allowed_to?(:see_logs) %>
							<li> <%= link_to t(:logs_list_title), logs_url %>
						<% end %>
					</ul>
				</li>
			<% end %>
			<li> <%= link_to t(:form_user_show_title), current_user %>
				<ul class="sub_menu">
					<li> <%= link_to t(:profile), current_user %> </li>
					<li> <%= link_to t(:contact), contact_url %> </li>
					<li> <%= link_to t(:logout), logout_url %>
				</ul>
			</li>
			
		</ul>
	</nav>
	<% end %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= render 'layouts/shim' %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag "favicon.ico" %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
		</div>
		<div class="container">
			<%= yield %>
		</div>
		<% if Rails.env.development? %>
		<div class="container">
			<%= debug(params) %>
		</div>
		<% end %>
	</body>
</html>